Feature/add codeowners
MOV-AI/movai-flow pull request #115
Opened 2022-05-03 09:33 UTC by MithunKinarullathil

- Control who needs to approve to merge to dev branch
- I will setup the rules after this merge

- [x] Make sure you are opening from a **topic/feature/bugfix branch**
- [x] Ensure that the PR title represents the desired changes
- [x] Ensure that the PR description detail the desired changes
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

[^note]:
    Put an `x` into the [ ] to show you have filled the information.
    The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
    You can override it by creating .github/pull_request_template.md  in your own repository

2022-05-03 15:23 UTC, AlexFernandes-MOVAI requested changes

2022-05-03 15:23 UTC, AlexFernandes-MOVAI commented on CODEOWNERS
> +*       @AlexFernandes-MOVAI @RianMartins-Movai @cormac-movai @MithunKinarullathil
- where do these names come from ? 
- should we have different rules for dev, main and releases/ branches ?

2022-05-03 16:06 UTC, MithunKinarullathil commented on CODEOWNERS
> +*       @AlexFernandes-MOVAI @RianMartins-Movai @cormac-movai @MithunKinarullathil
> * where do these names come from ?
> * should we have different rules for dev, main and releases/ branches ?

- It's been added manually by me based on the activity on the repository. 
- I think all branches should be restricted with at least one approval from codeowners. But since we cannot limit the main branch because of the automation bump issue, we won't be able to do that now. 
- For the codeowner functionality to be active, I think we need to change the permissions.

2022-05-04 15:48 UTC, AlexFernandes-MOVAI commented on CODEOWNERS
> +*       @AlexFernandes-MOVAI @RianMartins-Movai @cormac-movai @MithunKinarullathil
we can limit and have limited the main branch ;)

2022-05-16 12:16 UTC, MithunKinarullathil commented
This is not needed.

2022-05-16 12:16 UTC, closed without merging