Update latest releases link in README.md
MOV-AI/movai-flow pull request #143
Opened 2022-05-09 18:01 UTC by MithunKinarullathil

- Unfortunately, I am unable to find a dynamic link to the latest Debian file. @AlexFernandes-MOVAI Any black magic under your sleeves? 

- [x] Make sure you are opening from a **topic/feature/bugfix branch**
- [x] Ensure that the PR title represents the desired changes
- [x] Ensure that the PR description detail the desired changes
- [ ] ~~Link to relevant issues in GitHub or Jira~~
- [ ] ~~Link to relevant pull requests, esp. upstream and downstream changes~~
- [ ] ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~

[^note]:
    Put an `x` into the [ ] to show you have filled the information.
    The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
    You can override it by creating .github/pull_request_template.md  in your own repository

2022-05-10 08:42 UTC, AlexFernandes-MOVAI commented
`curl -s https://api.github.com/repos/MOV-AI/movai-flow/releases/latest | grep "browser_download_url.*deb" | cut -d : -f 2,3 | tr -d \"`

2022-05-10 08:51 UTC, AlexFernandes-MOVAI reviewed
You can also add a badge on top of the page:
[![github
release](https://img.shields.io/github/release/MOV-AI/movai-flow.svg?label=current+release)](https://github.com/MOV-AI/movai-flow/releases)
`[![github
release](https://img.shields.io/github/release/MOV-AI/movai-flow.svg?label=current+release)](https://github.com/MOV-AI/movai-flow/releases)`

2022-05-10 17:39 UTC, AlexFernandes-MOVAI requested changes

2022-05-10 17:39 UTC, AlexFernandes-MOVAI commented on README.md
> +Open a terminal, down the latest debian file and install it. Enter your user password if there is a promt.
download instead of  `down`

2022-05-10 17:39 UTC, AlexFernandes-MOVAI commented on README.md
>   - simulator: Ignition Fortress container with graphical capabilities enabled
why removing haproxy

2022-05-10 17:39 UTC, AlexFernandes-MOVAI commented on README.md
> +## Runing from source code
running instead of `runing`

2022-05-10 17:46 UTC, MithunKinarullathil commented on README.md
>   - simulator: Ignition Fortress container with graphical capabilities enabled
I thought we removed it, I will re-add.

2022-05-10 17:47 UTC, MithunKinarullathil commented on README.md
> +  <a href="https://twitter.com/MovAIRobots"><img alt="Twitter" src="https://img.shields.io/twitter/url/http/shields.io.svg?style=social"></a>
Need help.

2022-05-11 08:59 UTC, thetaleofnarutouzumaki commented on README.md
> +  <a href="https://twitter.com/MovAIRobots"><img alt="Twitter" src="https://img.shields.io/twitter/url/http/shields.io.svg?style=social"></a>
Done.

2022-05-11 09:10 UTC, AlexFernandes-MOVAI approved these changes

2022-05-11 09:11 UTC, merged