Stop exposing ros-master port and better health check
MOV-AI/movai-flow pull request #148
Opened 2022-05-12 12:54 UTC by MithunKinarullathil

- Remove exposed 11311, as it is currently stoping user from running roscore outside and since we don't have access to the topics in the host (yet), this is a pain
- Better healthcheck for roscore container

- [x] Make sure you are opening from a **topic/feature/bugfix branch**
- [x] Ensure that the PR title represents the desired changes
- [x] Ensure that the PR description detail the desired changes
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

[^note]:
    Put an `x` into the [ ] to show you have filled the information.
    The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
    You can override it by creating .github/pull_request_template.md  in your own repository

2022-05-12 13:48 UTC, AlexFernandes-MOVAI requested changes
Can you please indicate the use cases list you want to achieve with this PR ?
- better health check is one thing internal to the container : no problem to enhance it
- not exposing the port of ros-master is something more functional and feature oriented, I am afraid this change is not enough to reach the aimed feature

2022-05-12 14:13 UTC, MithunKinarullathil commented
This PR is just to close up a wound that is restricting the users without additional advantage. We have another good way to expose the ROS topics using the movai-cheatsheet, which has been tested thoroughly in the EE. It is better than exposing the full network to the host (which can have unintended consequences). So to summarize what this PR archives.

- User is able to run their own ROS launches and ROS things in their host independently with movi-flow running beside it. (currently, this is not possible if movai-flow is running, which is restricting function without providing additional value)

- For the short term we will document the steps from the cheat sheet, and how to expose topics manually to the community
- For the long term, once the cheatsheet tools are exposed, they will be able to do this easily using the cli.

2022-05-12 14:50 UTC, AlexFernandes-MOVAI commented
> This PR is just to close up a wound that is restricting the users without additional advantage. We have another good way to expose the ROS topics using the movai-cheatsheet, which has been tested thoroughly in the EE. It is better than exposing the full network to the host (which can have unintended consequences). So to summarize what this PR archives.
> 
> * User is able to run their own ROS launches and ROS things in their host independently with movi-flow running beside it. (currently, this is not possible if movai-flow is running, which is restricting function without providing additional value)
> * For the short term we will document the steps from the cheat sheet, and how to expose topics manually to the community
> * For the long term, once the cheatsheet tools are exposed, they will be able to do this easily using the cli.

OK, I got it. I will just complete that for the long term, I would recommend not  to have any CLI  at all ;)

2022-05-13 10:32 UTC, AlexFernandes-MOVAI approved these changes

2022-05-23 17:24 UTC, merged