Update links to flow components
MOV-AI/movai-flow pull request #154
Opened 2022-05-13 10:19 UTC by MithunKinarullathil

TODO: Open source
- spawner
- ros-tools
- haproxy

- [x] Make sure you are opening from a **topic/feature/bugfix branch**
- [x] Ensure that the PR title represents the desired changes
- [x] Ensure that the PR description detail the desired changes
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

[^note]:
    Put an `x` into the [ ] to show you have filled the information.
    The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
    You can override it by creating .github/pull_request_template.md  in your own repository

2022-05-13 10:29 UTC, AlexFernandes-MOVAI commented
nice one, thanks ;)

2022-05-13 10:30 UTC, AlexFernandes-MOVAI commented
Also, I believe we should start to have a dedicated installation.md to shorten a bit our main README.md

2022-05-13 10:42 UTC, MithunKinarullathil commented
> Also, I believe we should start to have a dedicated installation.md to shorten a bit our main README.md

https://github.com/MOV-AI/movai-flow/issues/155

2022-05-17 12:15 UTC, AlexFernandes-MOVAI requested changes

2022-05-17 15:06 UTC, MithunKinarullathil commented on README.md
> + - [haproxy](https://github.com/MOV-AI/containers-haproxy): Web proxy
Is it this one? https://github.com/haproxy/haproxy
I don't see the 2.4.15 tag there in the repository.

2022-05-23 17:24 UTC, MithunKinarullathil commented on README.md
> + - [haproxy](https://github.com/MOV-AI/containers-haproxy): Web proxy
@AlexFernandes-MOVAI ?

2022-06-14 13:03 UTC, AlexFernandes-MOVAI commented on README.md
> + - [haproxy](https://github.com/MOV-AI/containers-haproxy): Web proxy
https://hub.docker.com/_/haproxy

2022-06-21 09:29 UTC, AlexFernandes-MOVAI approved these changes

2022-06-21 09:37 UTC, merged