Develop/v2.4.0
MOV-AI/movai-flow pull request #212
Opened 2022-12-12 16:38 UTC by engdorm

updated to the latest code and docker images
contains the latest code from the backend and frontend

2022-12-14 08:13 UTC, engdorm commented
@AlexFernandes-MOVAI Can you help with the CI 
something went wrong with the ros container

2022-12-14 09:21 UTC, MithunKinarullathil commented
This releases/3.0.1 seems to be very old than the current main. Can you make a new releases branch from main and redo this PR? Syncing it would make another pre-release build I think, which we don't want.

2023-02-28 21:41 UTC, AlexFernandes-MOVAI requested changes

2023-02-28 21:41 UTC, AlexFernandes-MOVAI commented on docker-compose.yml
> +      DEFAULT_PASSWORD: www.mov.ai
take care of adapting the sanity test:
https://github.com/MOV-AI/movai-flow/blob/7a5659fde16fcda36ff8b1569e226bfaf2ff017e/.github/workflows/TestOnPR.yml#L83

2023-02-28 21:41 UTC, AlexFernandes-MOVAI commented on docker-compose.yml
> +    # For DEV purpose:
we should make sure that all packages are published to `ppa-public`

2023-07-24 14:53 UTC, AlexFernandes-MOVAI commented
will be addressed by #225

2023-07-24 14:53 UTC, closed without merging