Dp-1104 update service settings in docker compose
MOV-AI/movai-flow pull request #225
Opened 2023-07-21 16:24 UTC by mariana-dias-alves

Fixes #

## Proposed Changes

  -
  -
  -

- [ ] Make sure you are opening from a **topic/feature/bugfix branch**
- [ ] Ensure that the PR title represents the desired changes
- [ ] Ensure that the PR description detail the desired changes
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

[^note]:
    Put an `x` into the [ ] to show you have filled the information.
    The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
    You can override it by creating .github/pull_request_template.md  in your own repository

2023-07-27 13:29 UTC, AlexFernandes-MOVAI requested changes

2023-07-27 13:29 UTC, AlexFernandes-MOVAI commented on docker-compose-host.yml
> +    image: ${MOVAI_REGISTRY:-pubregistry.aws.cloud.mov.ai}/ce/backend-noetic:2.4.1.35
please try and use ghcr here instead of pubregistry

2023-07-27 13:29 UTC, AlexFernandes-MOVAI commented on .github/workflows/TestOnPR.yml
> +          status_code=$(curl -k -s -o /dev/null --header 'Content-Type: application/json' -X POST --data '{"username":"movai","password":"www.mov.ai","remember":true,"domain":"internal"}' -w "%{http_
store username and password in a var, not to edit multiple times

2023-07-27 13:29 UTC, AlexFernandes-MOVAI commented on docker-compose-host.yml
> +    image: ${MOVAI_REGISTRY:-pubregistry.aws.cloud.mov.ai}/ce/backend-noetic:2.4.1.35
as agreed, it will be done in another PR

2023-07-27 13:33 UTC, Mograbi commented on docker-compose-host.yml
> +      test: pgrep -f "/usr/bin/python3 /usr/local/bin/flow_initiator"
flow_initiator is a python module and not a script
it should remain -m flow_initiator

2023-07-27 13:33 UTC, Mograbi commented on docker-compose.yml
> +      test: pgrep -f "/usr/bin/python3 /usr/local/bin/flow_initiator"
same as before

2023-07-27 13:33 UTC, Mograbi commented on scripts/movai-flow-launch
> +while [[ -z $( $DOCKER_COMPOSE_BIN -f "$compose_conf" exec -u movai spawner bash -c 'pgrep -f "/usr/bin/python3 /usr/local/bin/flow_initiator"') ]]
same as before

2023-07-27 13:58 UTC, mariana-dias-alves commented on docker-compose-host.yml
> +      test: pgrep -f "/usr/bin/python3 /usr/local/bin/flow_initiator"
The previous command did not work to launch the web app, so I verified the way the app was opened inside the container and it is using this new command

2023-07-27 13:59 UTC, mariana-dias-alves commented on docker-compose-host.yml
> +      test: pgrep -f "/usr/bin/python3 /usr/local/bin/flow_initiator"
![Screenshot from 2023-07-27 14-58-59](https://github.com/MOV-AI/movai-flow/assets/139454338/95cbc73d-1f38-4d8a-ad34-f6a8ffe16035)

2023-07-28 09:19 UTC, AlexFernandes-MOVAI requested changes
use github repo secret

2023-07-28 09:19 UTC, AlexFernandes-MOVAI commented on .github/workflows/TestOnPR.yml
> +  password: "www.mov.ai"
good practice is to use GitHub secret of the repo to store password

2023-07-28 09:19 UTC, AlexFernandes-MOVAI commented on docker-compose-host.yml
> +      test: pgrep -f "/usr/bin/python3 /usr/local/bin/flow_initiator"
@Mograbi  mariana is right, the health-check is based on what the docker entrypoint currently run

2023-07-28 09:19 UTC, AlexFernandes-MOVAI commented on docker-compose.yml
> +      test: pgrep -f "/usr/bin/python3 /usr/local/bin/flow_initiator"
docker entrypoint is set like this

2023-07-28 11:14 UTC, AlexFernandes-MOVAI approved these changes

2023-07-28 11:19 UTC, merged